# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/KDevelop/guitar-tuner/Vivado/audio/audio.srcs/sources_1/bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
# IP: The module: 'ip_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/KDevelop/guitar-tuner/Vivado/audio/audio.gen/sources_1/bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/KDevelop/guitar-tuner/Vivado/audio/audio.srcs/sources_1/bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
# IP: The module: 'ip_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/KDevelop/guitar-tuner/Vivado/audio/audio.gen/sources_1/bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
