# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/KDevelop/guitar-tuner/Vivado/sources/zedboard_master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xfft_0_0 || ORIG_REF_NAME==design_1_xfft_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_1_0/design_1_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1_0 || ORIG_REF_NAME==design_1_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detect_0_0/design_1_edge_detect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detect_0_0 || ORIG_REF_NAME==design_1_edge_detect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_vga_controller_0_0/design_1_vga_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vga_controller_0_0 || ORIG_REF_NAME==design_1_vga_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_0 || ORIG_REF_NAME==design_1_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arinsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rinsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awinsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_winsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_binsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_aroutsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_routsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_awoutsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_woutsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_boutsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_arni_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_rni_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_awni_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_wni_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_bni_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_s00a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_sarn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_srn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sawn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_swn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sbn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m00s2a_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m00arn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00rn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00awn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00wn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00bn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: bd/design_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_0 || ORIG_REF_NAME==design_1_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
