set_property SRC_FILE_INFO {cfile:c:/KDevelop/guitar-tuner/Vivado/audio_fft/audio_fft.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc rfile:../../../audio_fft.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/ctrl/axi_dma_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/KDevelop/guitar-tuner/Vivado/audio_fft/audio_fft.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc rfile:../../../audio_fft.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc id:2 order:EARLY scoped_inst:design_1_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/KDevelop/guitar-tuner/Vivado/audio_fft/audio_fft.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc rfile:../../../audio_fft.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc id:3 order:EARLY scoped_inst:design_1_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/KDevelop/guitar-tuner/Vivado/sources/zedboard_master.xdc rfile:../../../../sources/zedboard_master.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:C:/KDevelop/guitar-tuner/Vivado/sources/adventures_with_ip.xdc rfile:../../../../sources/adventures_with_ip.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:design_1_i/vga_controller_0/U0/fifo/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:design_1_i/vga_controller_0/U0/fifo/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:8 order:LATE scoped_inst:{design_1_i/smartconnect_0/inst/switchboards/i_nodes/i_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[0].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:9 order:LATE scoped_inst:{design_1_i/smartconnect_0/inst/switchboards/i_nodes/i_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[1].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
current_instance design_1_i/ctrl/axi_dma_0/U0
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK1/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. In multi channel mode, it is safe to ignore this." -from [get_pins -hier -quiet -filter {NAME =~*MM2S_SPLIT.I_COMMAND_MM2S_SPLITTER/vsize_data_int_reg[*]/C}]
current_instance
current_instance design_1_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_2 0.6
set_property src_info {type:SCOPED_XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.24
set_property src_info {type:SCOPED_XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D12" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B11" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G13" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F9" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D7" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A13" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F11" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A8" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B6" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G7" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C4" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A3" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:2 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:2 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N7" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M7" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:2 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:2 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R5" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:2 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:2 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F3" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W2" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G1" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:2 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:2 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:2 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:2 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:2 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:2 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:2 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:2 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:2 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:2 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:2 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U1" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:2 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA3" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:2 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:2 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:2 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:2 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:2 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:2 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:2 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:2 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:2 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:2 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:2 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:2 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:2 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:2 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:2 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA2" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P6" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:2 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:2 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N4" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:2 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:2 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:2 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M6" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L6" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L7" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:2 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:2 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J6" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:2 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J7" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:2 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K5" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:2 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K6" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:2 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:624 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:2 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:2 line:636 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:2 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:2 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:2 line:648 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:2 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:2 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F7" [get_ports "PS_CLK"]
current_instance
current_instance design_1_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
current_instance
set_property src_info {type:XDC file:4 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21  [get_ports {VGA_B[0]}];  # "VGA-B1"
set_property src_info {type:XDC file:4 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20  [get_ports {VGA_B[1]}];  # "VGA-B2"
set_property src_info {type:XDC file:4 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {VGA_B[2]}];  # "VGA-B3"
set_property src_info {type:XDC file:4 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {VGA_B[3]}];  # "VGA-B4"
set_property src_info {type:XDC file:4 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22 [get_ports {VGA_G[0]}];  # "VGA-G1"
set_property src_info {type:XDC file:4 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports {VGA_G[1]}];  # "VGA-G2"
set_property src_info {type:XDC file:4 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports {VGA_G[2]}];  # "VGA-G3"
set_property src_info {type:XDC file:4 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports {VGA_G[3]}];  # "VGA-G4"
set_property src_info {type:XDC file:4 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports {VGA_HS}];  # "VGA-HS"
set_property src_info {type:XDC file:4 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20  [get_ports {VGA_R[0]}];  # "VGA-R1"
set_property src_info {type:XDC file:4 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20  [get_ports {VGA_R[1]}];  # "VGA-R2"
set_property src_info {type:XDC file:4 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19  [get_ports {VGA_R[2]}];  # "VGA-R3"
set_property src_info {type:XDC file:4 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18  [get_ports {VGA_R[3]}];  # "VGA-R4"
set_property src_info {type:XDC file:4 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19  [get_ports {VGA_VS}];  # "VGA-VS"
set_property src_info {type:XDC file:4 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 33]];
set_property src_info {type:XDC file:4 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 34]];
set_property src_info {type:XDC file:4 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 35]];
set_property src_info {type:XDC file:4 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 13]];
set_property src_info {type:XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA6 [get_ports BCLK]
set_property src_info {type:XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports BCLK]
set_property src_info {type:XDC file:5 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports LRCLK]
set_property src_info {type:XDC file:5 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LRCLK]
set_property src_info {type:XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7 [get_ports SDATA_I]
set_property src_info {type:XDC file:5 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SDATA_I]
set_property src_info {type:XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports SDATA_O]
set_property src_info {type:XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SDATA_O]
set_property src_info {type:XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2 [get_ports FCLK_CLK2]
set_property src_info {type:XDC file:5 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports FCLK_CLK2]
set_property src_info {type:XDC file:5 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4 [get_ports iic_0_scl_io]
set_property src_info {type:XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl_io]
set_property src_info {type:XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports iic_0_sda_io]
set_property src_info {type:XDC file:5 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda_io]
set_property src_info {type:XDC file:5 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1 [get_ports {gpio_tri_io[0]}]
set_property src_info {type:XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[0]}]
set_property src_info {type:XDC file:5 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5 [get_ports {gpio_tri_io[1]}]
set_property src_info {type:XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[1]}]
current_instance design_1_i/vga_controller_0/U0/fifo/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance design_1_i/vga_controller_0/U0/fifo/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {design_1_i/smartconnect_0/inst/switchboards/i_nodes/i_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[0].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
current_instance
current_instance {design_1_i/smartconnect_0/inst/switchboards/i_nodes/i_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[1].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
