# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/adventures_with_ip.xdc

# Block Designs: bd/ip_design/ip_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design || ORIG_REF_NAME==ip_design} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_0 || ORIG_REF_NAME==ip_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_xbar_0 || ORIG_REF_NAME==ip_design_xbar_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_ps7_0_axi_periph_0/ip_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==ip_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_rst_ps7_0_100M_0/ip_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==ip_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_0_0 || ORIG_REF_NAME==ip_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_1_0 || ORIG_REF_NAME==ip_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xfft_0_0/ip_design_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_xfft_0_0 || ORIG_REF_NAME==ip_design_xfft_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_dma_0_0/ip_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_dma_0_0 || ORIG_REF_NAME==ip_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xbar_1/ip_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_xbar_1 || ORIG_REF_NAME==ip_design_xbar_1} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_interconnect_0_0/ip_design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_interconnect_0_0 || ORIG_REF_NAME==ip_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xlconstant_0_0/ip_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_xlconstant_0_0 || ORIG_REF_NAME==ip_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_pc_0 || ORIG_REF_NAME==ip_design_auto_pc_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_us_0/ip_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_us_0 || ORIG_REF_NAME==ip_design_auto_us_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_us_1/ip_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_us_1 || ORIG_REF_NAME==ip_design_auto_us_1} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_pc_1/ip_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_pc_1 || ORIG_REF_NAME==ip_design_auto_pc_1} -quiet] -quiet

# XDC: c:/KDevelop/guitar-tuner/Vivado/audio/audio.gen/sources_1/bd/ip_design/ip_design_ooc.xdc
